# Generated by Django 4.1.8 on 2023-04-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='email_id',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
