# Generated by Django 4.1.8 on 2023-04-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeManager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credential',
        ),
    ]
