# Generated by Django 4.1.8 on 2023-04-27 09:46

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FridgeManager', '0002_delete_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('depth', models.FloatField()),
                ('expiration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_user', models.EmailField(max_length=254)),
                ('ref_height', models.IntegerField(default=0)),
                ('ref_width', models.IntegerField(default=0)),
                ('ref_depth', models.IntegerField(default=0)),
                ('fridge_height', models.IntegerField(default=0)),
                ('numberFridgeShelves', models.IntegerField(default=0)),
                ('freezer_height', models.IntegerField(default=0)),
                ('numberFreezerShelves', models.IntegerField(default=0)),
                ('fridgevolume', models.FloatField(default=0)),
                ('freezervolume', models.FloatField(default=0)),
                ('availablefridgevolume', models.FloatField(default=0)),
                ('availablefreezervolume', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_user', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('depth', models.FloatField()),
                ('items_list', djongo.models.fields.JSONField(default=dict)),
                ('volumeFilled', models.FloatField(default=0)),
                ('availableVolume', models.FloatField()),
            ],
        ),
    ]
