# Generated by Django 4.1.8 on 2023-04-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeManager', '0004_credential_firstname_credential_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='firstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='credential',
            name='lastName',
            field=models.CharField(max_length=50),
        ),
    ]
