# Generated by Django 4.1.7 on 2023-04-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeManager', '0004_credential_fridgelist_alter_shelf_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='height',
            field=models.FloatField(),
        ),
    ]
