# Generated by Django 4.1.7 on 2023-04-27 13:08

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeManager', '0005_alter_shelf_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerator',
            name='userList',
            field=djongo.models.fields.JSONField(default=dict),
        ),
    ]
