# Generated by Django 4.1.8 on 2023-04-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeManager', '0005_alter_credential_firstname_alter_credential_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='username',
        ),
    ]
