# Generated by Django 4.1.8 on 2023-04-21 01:17

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeManager', '0006_remove_credential_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
