# Generated by Django 4.1.7 on 2023-04-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeManager', '0006_refrigerator_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='noFridges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='noUsers',
            field=models.IntegerField(default=0),
        ),
    ]
