# Generated by Django 4.1.8 on 2023-04-21 01:28

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeManager', '0007_fridge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freezer',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='name',
        ),
    ]
