# Generated by Django 4.1.8 on 2023-05-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeManager', '0007_credential_nofridges_refrigerator_nousers'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
