# Generated by Django 4.1.8 on 2023-04-21 01:41

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeManager', '0008_freezer_remove_fridge_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('shelf_depth', models.IntegerField(default=True)),
                ('shelf_width', models.IntegerField(default=True)),
                ('shelf_height', models.IntegerField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='freezer',
            name='freezer_depth',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='freezer',
            name='freezer_height',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='freezer',
            name='freezer_width',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='fridge',
            name='fridge_depth',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='fridge',
            name='fridge_height',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='fridge',
            name='fridge_width',
            field=models.IntegerField(default=True),
        ),
    ]
