# Generated by Django 4.1.8 on 2023-05-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeManager', '0008_item_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
