# Generated by Django 4.1.8 on 2023-04-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeManager', '0009_shelf_freezer_freezer_depth_freezer_freezer_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezer',
            name='freezer_depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freezer',
            name='freezer_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freezer',
            name='freezer_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='fridge_depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='fridge_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='shelf_depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='shelf_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='shelf_width',
            field=models.IntegerField(default=0),
        ),
    ]
