# Generated by Django 4.1.8 on 2023-04-21 02:28

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeManager', '0010_alter_freezer_freezer_depth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refridgerator',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
