# Generated by Django 4.1.8 on 2023-04-24 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FridgeManager', '0011_refridgerator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Freezer',
        ),
        migrations.DeleteModel(
            name='Fridge',
        ),
        migrations.DeleteModel(
            name='Refridgerator',
        ),
        migrations.DeleteModel(
            name='Shelf',
        ),
    ]
